// empty objects indicate that key has no responsibilities in this mode
export default function commandLayouts(key) {
  return {
    default: {
      topRow: [
        {},
        {
          label: "vi",
          type: "chord",
          detune: -1500,
          tonality: "minor",
          inversion: "root",
          hand: "left",
        },
        {
          label: "ii",
          type: "chord",
          detune: -1000,
          tonality: "minor",
          inversion: "2nd",
          hand: "left",
        },
        {
          label: "iii",
          type: "chord",
          detune: -800,
          tonality: "minor",
          inversion: "2nd",
          hand: "left",
        },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
      ],
      middleRow: [
        {},
        {
          label: "I",
          type: "chord",
          detune: -1200,
          tonality: "major",
          inversion: "2nd",
          hand: "left",
        },
        {
          label: "IV",
          type: "chord",
          detune: -700,
          tonality: "major",
          inversion: "1st",
          hand: "left",
        },
        {
          label: "V",
          type: "chord",
          detune: -1700,
          tonality: "major",
          inversion: "root",
          hand: "left",
        },
        {},
        {},
        { label: "2", type: "note", detune: 200, hand: "right" },
        { label: "3", type: "note", detune: 400, hand: "right" },
        { label: "5", type: "note", detune: 700, hand: "right" },
        { label: "6", type: "note", detune: 900, hand: "right" },
        {},
      ],
      bottomRow: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
      spaceBar: { label: "1", type: "note", detune: 0, hand: "right" },
    },
  }[key];
}
