export default function keyboardLayouts(key) {
  return {
    "us-en": {
      topRow: [
        { label: "q" },
        { label: "w" },
        { label: "e" },
        { label: "r" },
        { label: "t" },
        { label: "y" },
        { label: "u" },
        { label: "i" },
        { label: "o" },
        { label: "p" },
        { label: "[" },
        { label: "]" },
      ],
      middleRow: [
        { label: "a" },
        { label: "s" },
        { label: "d" },
        { label: "f" },
        { label: "g" },
        { label: "h" },
        { label: "j" },
        { label: "k" },
        { label: "l" },
        { label: ";" },
        { label: "'" },
      ],
      bottomRow: [
        { label: "z" },
        { label: "x" },
        { label: "c" },
        { label: "v" },
        { label: "b" },
        { label: "n" },
        { label: "m" },
        { label: "," },
        { label: "." },
        { label: "/" },
      ],
      spaceBar: { label: "" },
    },
  }[key];
}
