export default function keyboardLayouts(key) {
  return {
    "us-en": {
      topRow: [
        { letter: "q" },
        { letter: "w" },
        { letter: "e" },
        { letter: "r" },
        { letter: "t" },
        { letter: "y" },
        { letter: "u" },
        { letter: "i" },
        { letter: "o" },
        { letter: "p" },
        { letter: "[" },
        { letter: "]" },
      ],
      middleRow: [
        { letter: "a" },
        { letter: "s" },
        { letter: "d" },
        { letter: "f" },
        { letter: "g" },
        { letter: "h" },
        { letter: "j" },
        { letter: "k" },
        { letter: "l" },
        { letter: ";" },
        { letter: "'" },
      ],
      bottomRow: [
        { letter: "z" },
        { letter: "x" },
        { letter: "c" },
        { letter: "v" },
        { letter: "b" },
        { letter: "n" },
        { letter: "m" },
        { letter: "," },
        { letter: "." },
        { letter: "/" },
      ],
      spaceBar: { label: "Space" },
    },
  }[key];
}
